services:
  sqlserver:
    build: ./mssql
    container_name: dockerbdmonedassqlserverITM
    ports:
      - 1440:1433
    environment:
      SA_PASSWORD: "abcd1234*"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - red

volumes:
  sqlserver_data:

networks:
  red:
    driver: bridge